### ISSUE TITLE
core.feature should demonstrate failure

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cucumber-tck#1]
It's all happy path now. Detecting failure is a core feature :-)

**Comment by jbpros** [comment]
I'm glad you bring this up because I was wondering if failure handling should actually be included in core. Strictly speaking, it is _not_ necessary to run global features. When something is failing, a good old stack trace fills up the terminal/console.

IMHO, core should be as small as possible.

What about describing failure handling in the first non-core global feature?

On the other hand, stack traces might be a bit rough... WDYT?

**Comment by jbpros** [comment]
We had a discussion on #cucumber: failure handling will be core because we don't to open the door to false positives.

**Comment by jbpros** [comment]
Closed by [65c6112c](https://github.com/cucumber/cucumber-features/commit/65c6112cfa6a6a27bae6d2e42b0b10824bd12bc9).
